### ISSUE TITLE
global configuration of years

### ISSUE THREAD

**Issue by MichalPP** [Scriptim/PrisonersDilemma#4]
add global configuration of RPST variables of years in prison (either by global js variables or GUI), then
* make use of it in all instances
* change years in the description (index.html) based on these data

(I start to use it in my class, to experiment with algorithms)

**Comment by Scriptim** [comment]
This repo is a school project and I have no concrete plans to develop it further. Maybe I'll take care of the issues when I'm bored, but I can't promise that. However, if you want to contribute, you can create a PR, I'd take a look at it.
